[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; media-src 'self' https:; object-src 'none'; base-uri 'self'; form-action 'self';"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for Netlify deployment
[context.production.environment]
  VITE_SUPABASE_URL = "https://demo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "demo_anon_key_placeholder"
  VITE_ALGORAND_NETWORK = "testnet"

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = "https://demo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "demo_anon_key_placeholder"
  VITE_ALGORAND_NETWORK = "testnet"

[context.branch-deploy.environment]
  VITE_SUPABASE_URL = "https://demo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "demo_anon_key_placeholder"
  VITE_ALGORAND_NETWORK = "testnet"